apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-py-deploy
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: tiny0wizard/app_visits:latest
        ports:
        - containerPort: 5000